modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/Lymia/CaveBiomeAPI-EmbeddiumCompat/issues"
license = "LGPL-3.0"

[[mods]]
    modId = "cavebiomeapi-embeddiumcompat"
    version = "${version}"
    authors = "Lymia Kanokawa"
    displayName = "CaveBiomeAPI (Embeddium Compat)"
    description = '''This mod adds compatibility between CaveBiomeAPI and Embeddium.'''
