modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/Lymia/SimpleCaveBiomes/issues"
license = "LGPL-3.0"

[[mods]]
    modId = "simplecavebiomes"
    version = "${version}"
    authors = "Lymia Kanokawa"
    displayName = "SimpleCaveBiomes"
    description = '''An alternative mod for cave biomes on 1.16'''

[[dependencies.simplecavebiomes]]
    modId = "forge"
    mandatory = true
    versionRange = "[36,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.simplecavebiomes]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.16.5,1.17)"
    ordering = "NONE"
    side = "BOTH"

[[mods]]
    modId = "cavebiomeapi"
    version = "1.4.2"
    authors = "Lymia Kanokawa"
    displayName = "SimpleCaveBiomes (CaveBiomeAPI Compat)"
    description = '''The compatibility library to allow SimpleCaveBiomes to be used in place of CaveBiomeAPI'''
